[build]
  command = 'npm run ci:build'
  publish = 'out'

[template]
  incoming-hooks = ["Uniform"]

[template.environment]
  SANITY_PROJECT_ID='Sanity Project ID'
  SANITY_DATASET='Sanity Dataset Name'
  UNIFORM_API_KEY='Uniform Optimize API Key'
  UNIFORM_PROJECT_ID='Uniform Optimize Project ID'
  GA_UA_ID='Google Analytics ID (optional)'
  NETLIFY_NEXT_PLUGIN_SKIP='Skip Netlify Next Plugin (set to true)'

# Stores the next cache between builds for faster build time
[[plugins]]
  package = "netlify-plugin-cache-nextjs"


[build.environment]
  UNIFORM_CLI_BASE_URL='https://canary.uniform.app'
